### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/elixir#573]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [x] [Configure online editor](https://github.com/exercism/elixir/issues/564)
- [x] [Add key features](https://github.com/exercism/elixir/issues/565)
- [x] [Add tags](https://github.com/exercism/elixir/issues/566)
- [x] [Add prerequisites to Practice Exercises](https://github.com/exercism/elixir/issues/567)
- [x] [Update status of track](https://github.com/exercism/elixir/issues/571)
- [x] [Update status of Concept Exercises](https://github.com/exercism/elixir/issues/572)
- [x] [Pass linting checks](https://github.com/exercism/elixir/issues/568)
- [x] [Build Test Runner](https://github.com/exercism/elixir/issues/569)
- [x] [Build Analyzer and Representer](https://github.com/exercism/elixir/issues/570) (optional)
- [x] [Add blurb to Concept Exercises](https://github.com/exercism/elixir/issues/680)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7

**Comment by angelikatyborska** [comment]
3️⃣, 2️⃣, 1️⃣, 🚀
